#!/usr/bin/env python3
import sqlite3
import re
from pathlib import Path

DB_PATH = Path("data/bootcamp.db")

NEW_CORE_CONCEPTS = {
    2: """
<p>Your mouse and keyboard are the two main tools you use to communicate with a computer. Think of them like the <strong>steering wheel and pedals</strong> of a car — the car can do nothing until you touch those controls. Mastering them means you work faster, make fewer mistakes, and feel more confident at any computer. When you first sit down at a desk, the mouse might feel slippery or overly sensitive, but with practice, it becomes an extension of your own hand.</p>
<p><strong>The Mouse Controls</strong></p>
<p>Move the mouse on a flat surface and a small arrow (called the <em>cursor</em>) moves on screen. The cursor is your hand inside the digital world. There are four core mouse actions that you will use constantly. A <strong>single left-click</strong> is used to select an item or position your cursor in a text box. A <strong>double left-click</strong> opens a file, folder, or program. A <strong>right-click</strong> is a magic shortcut: it opens a <em>context menu</em> containing actions you can take on that specific item. Finally, <strong>click and drag</strong> involves holding the left button down while moving the mouse, which lets you move files or select blocks of text.</p>
<p><strong>The Keyboard and Shortcuts</strong></p>
<p>The keyboard lets you input text, but it is also a command console. <em>Keyboard shortcuts</em> are combinations of keys that perform actions instantly, saving you from navigating complex menus. For example, pressing <strong>Ctrl + C</strong> copies a selection, and <strong>Ctrl + V</strong> pastes it. If you make a mistake, <strong>Ctrl + Z</strong> is your safety net — it undoes your last action immediately. To save your progress, always use <strong>Ctrl + S</strong>.</p>
<p>Think of learning keyboard shortcuts like learning the <strong>danfo bus routes</strong> in Lagos or the <strong>matatu shortcuts</strong> in Nairobi. A novice traveler takes the main highway and gets stuck in heavy gridlock (navigating menus with a slow mouse). A seasoned commuter knows the quick shortcuts through backstreets and side roads, arriving at their destination in a fraction of the time. By committing these core shortcut keys to memory early on, you bypass the digital traffic jam and navigate your computer like a professional.</p>
""",
    3: """
<p>Every single file on your computer has a home — a specific location in a system of folders. Understanding this system is like learning the layout of a large, bustling market like <strong>Balogun Market in Lagos</strong> or <strong>Kariakoo in Dar es Salaam</strong>. If you walk into a market with no map, looking for a specific merchant, you could wander for hours in the heat. But if you know that the market is divided into zones — fabrics in one lane, electronics in another, spices in a third — you can walk straight to what you need. A computer organizes your files in exactly the same structured way.</p>
<p><strong>The Folder Tree</strong></p>
<p>Your computer organises storage in a parent-child hierarchy called a folder tree. At the very top is the hard drive, usually labeled <em>Local Disk C:</em>. Inside it are major folders like <em>Users</em>. Inside the Users folder is your personal folder (named after you), which contains your daily folders: <em>Documents</em>, <em>Downloads</em>, <em>Desktop</em>, and <em>Pictures</em>. A <em>file path</em> describes exactly where a file lives, acting like a physical address. For example, <strong>C:\\Users\\Amara\\Documents\\my_biography.docx</strong> tells the computer to open the C drive, go into the Users folder, find Amara's folder, open Documents, and retrieve that specific file.</p>
<p><strong>Managing Your Files</strong></p>
<p>To browse this map, you use <strong>File Explorer</strong> on Windows or <strong>Finder</strong> on macOS. You can move files by using <strong>Cut (Ctrl + X)</strong> and <strong>Paste (Ctrl + V)</strong>, which removes the file from its old home and places it in a new folder. If you want to make a duplicate, use <strong>Copy (Ctrl + C)</strong>. You can rename files to keep them organized, or delete them to send them to the Recycle Bin. A key professional habit is using consistent file naming conventions (like using underscores instead of spaces, e.g., <code>Amara_Biography_Draft.docx</code>) and avoiding desktop clutter. If you leave every file on your desktop, it is like a trader dumping their entire stock in a heap at the entrance of the market stall.</p>
""",
    4: """
<p>A word processor is software that lets you write, edit, and format text documents — like a typewriter, but far more powerful. The most common ones are <strong>Microsoft Word</strong>, <strong>Google Docs</strong>, and <strong>LibreOffice Writer</strong>. All three work similarly: you type in a large white space, and a toolbar at the top gives you formatting options. The interface features a blank canvas and a toolbar containing buttons for font styles, sizing, bold, italics, alignment, and spacing. When you type, your text default to basic settings, but as a digital professional, you must learn to format it with intention.</p>
<p><strong>The Art of Tailoring Documents</strong></p>
<p>Think of document formatting like tailoring a beautiful piece of <strong>Kente fabric in Ghana</strong> or <strong>Ankara fabric in Nigeria</strong>. When a tailor receives a plain roll of cotton cloth, it is simple and unformed — much like a document containing raw, unformatted text. The tailor does not just hand the roll of cloth to the client. They cut it carefully, sew neat borders, add colorful embroidery, and shape it so that it is beautiful and fits the client perfectly. Formatting a document is the digital equivalent of this craftsmanship. Your <strong>Heading 1 (H1)</strong> title is the main border of the garment; your <strong>bold (Ctrl+B)</strong> or <strong>italic (Ctrl+I)</strong> text additions are the special embroidery that draws attention; and your paragraph spacing is the cut that lets the garment breathe. Without these structural elements, your document is just a confusing heap of raw thread.</p>
<p><strong>Key Formatting Rules</strong></p>
<p>To make a professional impression, always use a clear title at the top, separate distinct thoughts into short paragraphs of 3–5 sentences, use proper capitalisation at the start of sentences, and press Enter twice between paragraphs to leave clean breathing space. Always save your document early and often using <strong>Ctrl + S</strong>, and save it with a clear, descriptive filename in the correct folder, checking that it has the correct file extension like <code>.docx</code>.</p>
""",
    5: """
<p>In the first four days of this bootcamp, you have covered enormous ground. You learned what a computer is, how to control it with a mouse and keyboard, how to navigate and organise files, and how to create a formatted document. Today is not about learning something entirely new — it is about <strong>consolidating and organising</strong> everything you have done. It is a day to step back, review your progress, and build a clean digital architecture that will support your learning for the remaining weeks.</p>
<p><strong>The Market Display Analogy</strong></p>
<p>Think of it like a trader at the bustling <strong>Makola Market in Accra</strong> or <strong>Kejetia Market in Kumasi</strong>. At the start of the week, a smart trader does not just throw all their tomatoes, plantains, and peppers into one big pile on the ground. If they did, customers would get confused, the stock would get damaged, and the trader would waste time searching for items. Instead, the trader sweeps their stall, arranges wooden crates, and sorts their goods into clean, labeled baskets. This organization makes their business attractive and efficient. Cleaning up your computer's desktop and setting up a structured folder system is your digital equivalent of tidying up your market stall. It shows that you respect your work and value your time.</p>
<p><strong>The Principle of One Home Per File</strong></p>
<p>Every file you create must live in one logical place with a clear, descriptive name. Vague names like <code>document1.docx</code> or <code>untitled.txt</code> cause confusion and lead to lost files. By establishing a system like the <code>MY DIGITAL LIFE</code> folder tree, you create a professional framework. When you move your week's exercises into a dedicated <code>Week 1 Review</code> folder, you are building the foundation of a digital portfolio. This portfolio is a curated showcase of your skills that you can eventually share with potential employers, demonstrating your digital competence and organizational ability from day one.</p>
""",
    6: """
<p>The internet is not a place — it is a <strong>global network of computers</strong> connected by undersea cables, satellite signals, and radio waves. When you load a webpage, your computer sends a tiny request that travels to another computer (called a <em>server</em>) that holds that page, and the server sends it back in fractions of a second. This data travels through a massive physical infrastructure stretching across continents, under oceans, and through local cell towers before reaching your screen.</p>
<p><strong>The Mobile Money Network Analogy</strong></p>
<p>Think of the internet like the <strong>mobile money network</strong> (such as <strong>M-Pesa in Kenya</strong>, <strong>MTN Mobile Money in Ghana</strong>, or <strong>Orange Money in Senegal</strong>). When you send money to a relative, you do not physically carry cash across the country. Your phone sends a digital request through your local network provider. This request travels through servers and cell towers, checks the recipient's identity, transfers the digital balance, and sends a confirmation SMS. The internet works on the exact same principle: requests and responses moving through invisible infrastructure. Your browser acts like the mobile money agent's kiosk — the friendly interface where you initiate your transactions and receive your results.</p>
<p><strong>Browsers, URLs, and Security</strong></p>
<p>A web browser is the software you use to navigate the web (Chrome, Firefox, Safari). The address bar is where you type a <em>URL</em> (Uniform Resource Locator) — the unique address of a webpage. A URL contains the protocol (like <em>https://</em>, which encrypts your connection), the domain name (like <code>wikipedia.org</code>), and a path to a specific page. The padlock icon in the browser address bar is crucial. It means your connection is secure and encrypted, protecting your data from interception. Always look for this padlock, especially when accessing websites from public business centers or internet cafés. Bookmarks are another essential tool, allowing you to save important URLs so you can return to them instantly with a single click, like saving a frequent contact on your mobile phone.</p>
""",
    7: """
<p>Most people use Google every day, but few use it well. Typing a vague phrase like <em>news about Africa</em> returns millions of results. Typing a precise query like <em>"renewable energy" Nigeria 2024 site:bbc.com</em> returns exactly what you need. The difference is <strong>search skill</strong>. Search engines index billions of web pages, but they are literal-minded tools that require clear, targeted keywords to give you the most relevant results.</p>
<p><strong>The Market Guide Analogy</strong></p>
<p>Think of a search engine like a very experienced helper at a massive market like <strong>Ariaria International Market in Aba</strong>. If you enter the market and tell the helper, "I want something nice," the helper will be lost and might lead you to random stalls selling clothes, food, or shoes. But if you tell them, "I need a wholesale vendor who sells locally made leather shoes from Nigeria," they can take you directly to the correct corridor in minutes. The helper is highly efficient, but they rely entirely on the specificity of your instructions. In the digital world, your search query is that instruction.</p>
<p><strong>Formulating Better Queries</strong></p>
<p>To get the best results, use specific keywords instead of long questions. For example, instead of searching <em>where is the capital of Ghana and what is its name</em>, use <code>Ghana capital city name</code>. You can use search operators to narrow your results: put exact phrases in quotes (e.g., <code>"longest river in Africa"</code>) to match those exact words, add a specific year (e.g., <code>Nigeria population 2025</code>) to get the most recent data, or use <code>site:</code> to search within a specific trusted website (e.g., <code>site:wikipedia.org</code>). Always evaluate your sources before trusting them. Check who published the information, look for established educational or news organizations, and verify if other reputable websites agree. Building these research habits protects you from misinformation.</p>
""",
    8: """
<p>Email is the standard form of professional written communication in almost every industry. Whether you are applying for a job, communicating with a client, or following up on an assignment, a well-written email makes a strong impression. A poorly written one can close doors before you even knock. In the digital workplace, email is formal, archived, and considered a legal record of communication. Unlike chat messages, it requires structure, politeness, and attention to detail.</p>
<p><strong>The Courier Analogy</strong></p>
<p>Think of an email like a <strong>formal letter</strong> sent via a professional courier or dispatch rider (like a <strong>GIG Logistics rider in Lagos</strong> or a <strong>Boda Boda delivery service in Kampala</strong>). If you write a formal business proposal to a partner, you do not scribble it on a scrap of paper and shout it across the street. You write it on clean stationery, address it to a specific person, sign it with your name, place it in an envelope, and hand it to a courier to deliver. The email system is the digital version of this process. The <strong>To:</strong> field is the address on the envelope, the <strong>Subject Line</strong> is the label on the package, the greeting and body are the formal letter inside, and the sign-off is your personal signature. Understanding this structure helps you convey respect and professionalism to the recipient.</p>
<p><strong>The Structure of a Professional Email</strong></p>
<p>Every professional email contains key components. The **Subject Line** must be clear and descriptive, such as <code>Job Application: Office Assistant - Amara Diallo</code>. Never leave it blank. The **Greeting** should address the person formally, using <code>Dear Mr. Kofi</code> or <code>Dear Dr. Chioma</code>. The **Body** should state your purpose in the first sentence and use short paragraphs of 2–4 sentences. Keep it concise. The **Sign-off** concludes the email with a professional phrase like <code>Kind regards</code> or <code>Sincerely</code>, followed by your full name and contact information. In Gmail, you will navigate this workflow using the <em>Compose</em> button to start, and check folders like <em>Inbox</em>, <em>Sent</em>, and <em>Drafts</em> to manage your messages.</p>
""",
    9: """
<p>Sending an email is easy. Sending an email that is clear, respectful, and professional is a true skill. Today, you go deeper into communication — learning to master tone, manage attachments, and build habits that separate effective digital workers from the crowd. Since written text lacks facial expressions or voice inflection, you must choose your words carefully to ensure your message is received as intended.</p>
<p><strong>The Market Shouting Analogy</strong></p>
<p>Think of email tone and etiquette like navigating a busy market. If you walk into a market and start shouting at the top of your lungs (using **ALL CAPS** in an email), people will find it aggressive and rude. If you use slang, text abbreviations (like <em>pls</em> or <em>thx</em>), or ignore greetings, it is like walking up to a trader's stand, grabbing their goods, and throwing money at them without saying a word. In contrast, greeting the trader politely, speaking clearly, and saying thank you creates a warm relationship. Professional email etiquette uses this same politeness. Always double-check your spelling, avoid informal abbreviations, and read your message aloud before hitting send to ensure your tone is professional and respectful.</p>
<p><strong>Managing Email Attachments</strong></p>
<p>An attachment is a file (document, PDF, photo) sent alongside your email. Think of it like attaching a copy of your national ID or certificate to a physical application form. Always name your files clearly before attaching them (e.g., <code>Amara_Diallo_Biography.pdf</code> instead of <code>document_123.pdf</code>) so the recipient knows what it is. Always mention the attachment in the body of the email (e.g., <em>"Please find my biography attached."</em>) so it is not missed. Keep in mind that email providers have file size limits (usually 25MB). If you need to send larger files, you should use cloud storage links instead of direct attachments. Finally, understand when to use <strong>Reply</strong> (to the sender only) versus <strong>Reply All</strong> (to everyone on the email thread) to avoid cluttering people's inboxes.</p>
""",
    10: """
<p>Writing a single paragraph of text is simple, but producing a multi-page professional report requires structure. Structure is what separates a confusing wall of text from an organized document that a reader can scan, navigate, and comprehend in minutes. By formatting your report with clear headings and styles, you make it easy for clients, supervisors, and partners to read and digest your work.</p>
<p><strong>The House Construction Analogy</strong></p>
<p>Think of document structure like building a modern house in **Nairobi** or **Abidjan**. You do not just build one big room and pile all the furniture, kitchen appliances, and beds inside it. If you did, the house would be unlivable. Instead, you design a layout with clear divisions. The main entrance gate is the **Heading 1 (H1)** title, welcoming visitors. The walls that divide the house into functional areas (like the living room, kitchen, and bedrooms) represent your **Heading 2 (H2)** section titles. The furniture and decorations placed inside each room represent your body text and paragraphs. Each room has a single purpose, and visitors can navigate the house without getting lost. In a document, this layout guides your reader from one topic to the next.</p>
<p><strong>Formatting for Paragraph Flow</strong></p>
<p>To achieve this, use your word processor's built-in **Heading Styles** (H1, H2, H3). This not only applies consistent fonts and sizes but also builds a navigation map that screen readers and table-of-contents tools can detect. When writing your paragraphs, follow the **PIE structure**: state your **Point** (the main idea), provide an **Illustration** (a detail or example), and offer an **Explanation** (connect it back to your main point). Keep your document clean by using left alignment, 1.15 or 1.5 line spacing, and double returns between paragraphs. This makes the text readable, ensuring your report looks professional and is easy on the eyes.</p>
""",
    11: """
<p>Anyone can copy and paste text from a website, but research is much more than that. Research is the skill of visiting multiple sources, comparing what they say, identifying what is credible and consistent, and then expressing those ideas in your own words. This is one of the most valued skills in any professional setting, showing that you can gather information and turn it into useful knowledge.</p>
<p><strong>The Market Inquiry Analogy</strong></p>
<p>Think of research and synthesis like asking a question to multiple traders at the **Kariakoo Market in Dar es Salaam** or the **Kejetia Market in Kumasi**. If you want to know if the price of maize is going up, you do not just ask the first seller you see and write down their answer as absolute truth. They might have a personal bias or high prices. Instead, you walk around, talk to three different traders in different rows, and listen to their explanations. You compare their answers: if all three say that low rainfall has caused a shortage, you can be confident the fact is correct. You then write down a summary of what you learned in your own words, rather than repeating their sentences word-for-word. This synthesis represents the truth of your findings.</p>
<p><strong>The Research and Citation Process</strong></p>
<p>To research professionally, choose a focused topic (e.g., <em>the benefits of solar energy in rural West Africa</em>). Visit at least three different websites, take notes on the main points in your own words, and save their web links. When you combine these notes into a final document, your voice should lead the explanation, supported by facts from your research. Always cite your sources by listing their URLs at the bottom. This allows readers to verify your facts and protects you from **plagiarism** — the act of presenting someone else's work as your own. In the academic and professional worlds, plagiarism is considered dishonest and can damage your reputation.</p>
""",
    12: """
<p>Downloading files from the internet is one of the most common online tasks — and one of the main ways that computers get infected with **malware** (harmful software). Learning to identify safe sources, verify file types, and organize what you download is a critical digital skill that protects your device and your personal data from cybercriminals.</p>
<p><strong>The Pharmacy Analogy</strong></p>
<p>Think of downloading files like buying medicine in a major city like **Accra** or **Nairobi**. If you need medicine, you do not buy it from an unlicensed street vendor selling loose pills from an unmarked box on the side of the road. The pills could be fake, expired, or harmful. Instead, you walk into a registered, licensed pharmacy with a clean shop and professional staff because you trust their source. Downloading files works the same way. Official websites and established media platforms (like **Unsplash** or **Pixabay** for free images) are like licensed pharmacies. Unfamiliar websites offering "free downloads" of expensive software or movies are like street vendors — they often bundle their downloads with hidden malware designed to steal your passwords or lock your files.</p>
<p><strong>Safe Downloading Habits</strong></p>
<p>To stay safe, always check the **file extension** before opening a downloaded file. An image file should end in <code>.jpg</code>, <code>.png</code>, or <code>.webp</code>. A document should end in <code>.docx</code> or <code>.pdf</code>. If you download what you think is a photo or a report, but the file name ends in <code>.exe</code> or <code>.bat</code>, do not open it. These extensions mean it is a program that will execute code on your computer, which is a classic delivery method for viruses. Pay attention to your browser's security warnings and never ignore them. Once a file is safely downloaded, immediately rename it from a generic code (like <code>IMG_3482.jpg</code>) to a descriptive name (like <code>lagos_market_kiosk.jpg</code>) and move it from your Downloads folder into a structured folder in your workspace.</p>
""",
    13: """
<p>Cybersecurity is not just for computer scientists or IT departments. Every person who connects a phone or computer to the internet is a potential target for digital criminals. Most digital attacks succeed not because they use advanced hacking code, but because they trick regular users into letting them in. Understanding common digital threats is your strongest and most practical line of defense.</p>
<p><strong>The Mobile Money Fraud Analogy</strong></p>
<p>Think of cybersecurity like protecting your mobile money account. In many places across Africa, fraudsters use **social engineering** to steal money. You might receive a phone call or SMS from an unknown number claiming to be from **MTN**, **Safaricom**, or your bank. The caller speaks with great urgency, saying: <em>"Your account has been suspended due to an upgrade! You must send us your OTP (One-Time Password) or dial this code to unlock it immediately."</em> If you panic and share your code, the fraudster logs in and sweeps your balance. Cybersecurity works on the same principle of manipulation. **Phishing** is the digital version of this trick, using fake emails, text messages, or WhatsApp links that look like official bank pages, asking you to click and log in so they can steal your password. Your defense is simple: pause, verify, and never share security codes.</p>
<p><strong>Common Threats and Red Flags</strong></p>
<p>Beyond phishing and social engineering, you must watch out for **malware** (viruses and spyware) that can be installed on your device when you click bad links. Always watch for red flags in messages: urgent or threatening language, mismatched sender email domains (such as <code>support@gtbank-login-update.net</code> instead of the official <code>gtbank.com</code>), and links that show a suspicious address when you hover your cursor over them. Protecting your accounts is a habit. Set up **Two-Factor Authentication (2FA)** on all your critical profiles, such as your email and banking portals. This requires two forms of proof to log in, making it nearly impossible for fraudsters to gain access even if they manage to steal your password.</p>
""",
    14: """
<p>Video conferencing has transformed how work happens globally. Remote teams meet, students attend classes, and freelancers present projects to international clients using platforms like **Google Meet**, **Zoom**, and **Microsoft Teams**. Knowing how to run a professional online meeting is now an essential skill. Conducting a successful virtual call requires understanding the software controls, managing your environment, and practicing proper etiquette.</p>
<p><strong>The Busy Market Street Analogy</strong></p>
<p>Think of hosting a virtual meeting like holding a business discussion in a physical office. If you leave your office door wide open to a busy market street or next to a loud diesel generator, your client will not hear you, and the conversation will fail. In the virtual world, your microphone is that open door. Background noise — traffic, barking dogs, loud music, or generators — is picked up by your microphone and broadcast to everyone in the meeting. This is why the **Mute button** is your most important control. Keep your microphone muted by default, and only unmute when you are actively speaking. When your turn is finished, close the door by muting yourself again. This simple habit shows respect for your colleagues' time and attention.</p>
<p><strong>Managing Connection and Controls</strong></p>
<p>In many regions, internet bandwidth can be unstable. If your connection becomes choppy or your data plan is running low, turn off your video camera to save data and prioritize your audio quality. Always test your camera angle and microphone before joining a call, ensuring you are in a quiet space with neutral lighting. During the call, utilize the **Screen Sharing** tool to show documents or presentations directly from your computer, allowing everyone to follow your explanation. Use the 'Raise Hand' feature to signal when you want to speak without interrupting, and check the chat box for shared links or typed questions. By mastering these controls, you ensure your online meetings are professional, efficient, and productive, regardless of where your participants are located.</p>
""",
    15: """
<p>Imagine your important business files, reports, and certificates are saved only on your personal laptop. If that laptop is stolen, damaged by water, or crashes, your work is gone forever. **Cloud storage** solves this problem. Instead of saving files only on your local hard drive, you save them on secure, remote servers managed by cloud providers (like Google Drive). This allows you to access your files from any phone, tablet, or computer, anywhere in the world, as long as you have an internet connection.</p>
<p><strong>The Mobile Wallet Analogy</strong></p>
<p>Think of cloud storage like keeping your money in a digital mobile money wallet or savings app (like **PiggyVest in Nigeria** or **MTN MoMo**), rather than keeping cash in a wooden drawer at your house. If you keep your cash under your mattress or in a drawer, it is vulnerable to theft, fire, or accidental loss. If your house is locked or damaged, you cannot access your money. Storing your files on a single laptop is like keeping that cash under your mattress. In contrast, putting your money in a mobile money system or digital bank vault means it is secure, backed up, and you can access your funds from any mobile phone or agent kiosk across the country. Google Drive is your digital bank vault for files. It gives you 15GB of free space to upload, organize, and back up your documents safely.</p>
<p><strong>Collaboration and Sharing</strong></p>
<p>The true power of cloud storage is collaboration. Instead of emailing large files back and forth (which can easily fail due to file size limits), you generate a **Shareable Link** to the file stored in the cloud. You can share this link via email or WhatsApp. You control the **permission level** of the link: you can set it to **Viewer** (read-only), **Commenter** (can suggest edits), or **Editor** (can modify the file). This allows multiple team members to work on the same report simultaneously without creating duplicate versions, streamlining remote collaboration.</p>
""",
    16: """
<p>Your password is the lock on the front door of your digital life. If the lock is weak — like using a simple word, your birthday, or <em>password123</em> — a criminal can easily pick it. Once inside, they have full access to your email, bank accounts, personal photos, and contacts. Creating strong passwords and enabling Two-Factor Authentication (2FA) are the most effective and practical actions you can take to protect your online identity.</p>
<p><strong>The Secure Compound Analogy</strong></p>
<p>Think of your account security like protecting a compound in a busy city. A password is the key to the main front gate. If you use a simple, common padlock, anyone can buy a master key or break it with a basic tool. Furthermore, if you use the exact same key for your front gate, your shop, and your storage room, a thief who steals that single key now has access to everything. This is why you must use unique, strong passwords for every account. But even if you have a strong lock, someone could steal your key or copy it while you are not looking (which represents a data breach or phishing attack).</p>
<p>To prevent this, you add **Two-Factor Authentication (2FA)**. This is like hiring a watchman at your gate. Even if a visitor approaches the gate and unlocks it with a copied key, the watchman stops them and says: <em>"I see you have the key, but I must send a verification SMS code to the owner's phone. You cannot enter until they read me the code."</em> The visitor cannot get in without your phone. This second layer of verification is what keeps hackers out, even if they know your password.</p>
<p><strong>Best Security Practices</strong></p>
<p>A strong password must be at least 12 characters long and include a mix of uppercase letters, lowercase letters, numbers, and symbols. Since remembering unique passwords for every account is difficult, use a **Password Manager** — a secure digital vault that generates and remembers strong passwords for you. Enable 2-Step Verification on your Google account and other key platforms immediately to ensure your accounts are ironclad.</p>
""",
    17: """
<p>Artificial intelligence tools have moved from science fiction to everyday reality. Tools like ChatGPT, Claude, and Gemini are now used by professionals, writers, and entrepreneurs worldwide to work faster and smarter. Understanding what these tools are — and learning where their limitations lie — is a critical skill that will put you ahead of the majority of computer users.</p>
<p><strong>The Workshop Apprentice Analogy</strong></p>
<p>Think of an AI language model like a new **apprentice in a carpentry or tailoring workshop** in **Kumasi** or **Benin City**. The apprentice is incredibly eager and has read every master manual and textbook in the world. They can tell you the theory of how to design a table or sew a suit, and they can write a detailed plan for it in seconds. However, the apprentice has never actually touched wood or fabric. They have no eyes of their own, no real-world experience, and cannot feel if a material is of high quality. If you ask them to build something without instructions, they might make up a design that looks plausible but falls apart (which is called an AI **hallucination**). As the master craftsman, you must give them clear directions, supervise their progress, and double-check all their stitches before presenting the work. The AI is your helper, but you remain the expert in charge.</p>
<p><strong>Capabilities and Limitations</strong></p>
<p>AI tools excel at explaining complex concepts in simple terms, drafting business templates, brainstorming creative ideas, and summarizing long documents. However, they are not reliable for up-to-date factual research because their training data has a cutoff date. They also cannot make decisions or provide professional legal or financial advice. Always treat AI as a draft generator, never as the final word. By maintaining a critical approach — using AI to assist while you remain the judge of accuracy and tone — you harness the true power of your digital copilot.</p>
""",
    18: """
<p>Yesterday, you interacted with an AI tool for the first time. Today, you go deeper: you learn to communicate with AI intentionally. The quality of what an AI generates is directly tied to the quality of your prompt. A vague question gets a vague, generic answer. A precise, structured prompt gets professional, high-quality output. The skill of crafting these instructions is called **Prompt Engineering**.</p>
<p><strong>The Kitchen Order Analogy</strong></p>
<p>Think of prompting an AI like ordering food at a local kitchen in **Lagos** or **Accra**. If you walk up to the cook and say, <em>"Bring me something to eat,"</em> you are leaving the decision completely to them. They might bring you a bowl of hot pepper soup when you actually wanted a solid meal, or a plate of rice containing ingredients you dislike. You cannot complain because your order was too vague. However, if you order specifically: <em>"I would like a plate of Jollof rice with grilled chicken, medium spice, with a side of plantain and no onions,"</em> the cook can prepare exactly what you want. You get a perfect meal because your instructions were detailed. Prompting an AI works in the same way. You must specify the role, context, output format, and constraints to get the best results.</p>
<p><strong>Structuring Role-Based Prompts</strong></p>
<p>One of the most effective prompting structures is the **Role-Based Prompt**. You begin by telling the AI who to act as (e.g., <em>"Act as a professional career coach"</em>). Then, you provide context (e.g., <em>"I am a beginner who just completed a digital skills bootcamp"</em>), specify the task (e.g., <em>"Write a CV summary"</em>), and set constraints (e.g., <em>"Keep it under three sentences and write in a formal tone"</em>). This structure guides the AI to use patterns from expert writing in its database. If the first response is not perfect, you can iterate by adding feedback (like <em>"make it more concise"</em>) until the output meets your professional standards.</p>
""",
    19: """
<p>Over the past 18 days of this bootcamp, you have created real digital work: a formatted biography, a travel report, research documents, cybersecurity audits, and AI experiments. Today, you stop and look at everything you have built. You will learn to organize and showcase this work in a **Digital Portfolio** — a curated collection of your best projects that proves your skills to potential employers, clients, or instructors.</p>
<p><strong>The Tailor Shop Window Analogy</strong></p>
<p>Think of your digital portfolio like a **tailor's shop window display** in a busy shopping district of **Lagos** or **Nairobi**. A master tailor does not crowd their front window with scraps of fabric, sewing threads, tape measures, and half-finished trousers. If they did, their shop would look messy, and customers would pass by without entering. Instead, the tailor carefully selects three or four of their most beautiful, finished garments — a perfectly tailored suit, a vibrant native dress, and a neatly embroidered shirt — and displays them under clean lights. This window display proves their craftsmanship at a single glance. Your digital portfolio is that shop window. You do not show every draft or mistake; you select your best, completed documents, name them clearly, and organize them so that a visitor is immediately impressed by your professional capabilities.</p>
<p><strong>Curation and Organization</strong></p>
<p>A portfolio stands out because of its neatness. In the digital economy, recruiters and clients look at how you name files and organize folders before they even read your content. If they see a shared folder named <code>[YourName]_Digital_Portfolio</code> containing clearly labeled, professional files, it proves you are structured. When you upload your key files to Google Drive and set the sharing link to "Anyone with the link can view", you create a shareable career asset. This link can be added to your CV or shared on WhatsApp, opening doors to freelance work and employment opportunities.</p>
""",
    20: """
<p>You have reached Day 20 — the final day of the Dako Studios Digital Skills Bootcamp. Over these twenty days, you have traveled from learning the basic physical parts of a computer to managing cloud storage, defending against cyber scams, and directing AI tools with professional prompts. This is a remarkable achievement, and today you consolidate that growth. Your final project is a **Capstone Project** — a comprehensive task that brings together all the skills you have developed.</p>
<p><strong>The Trade Fair Stand Analogy</strong></p>
<p>Think of your final Capstone Graduation Hub like setting up a business exhibition stand at the **Lagos International Trade Fair** or the **Nairobi Agricultural Show**. If you are exhibiting your products, you do not just dump all your brochures, product samples, banners, and business cards in a disorganized heap on a table. If you did, visitors would walk away confused. Instead, you design a welcoming stand. You put up a clear sign, set up two neat tables — one for your basic brochures and credentials, and another for your active product demonstrations — and place a guestbook for visitors to write reflections. This layout is what makes your stand professional. Your Graduation Hub works the same way. By creating a master folder containing structured sub-folders like <code>01_Foundations</code> and <code>02_Projects</code>, you build a digital showroom that displays your skills. Adding a personal **Reflective Writing** summary is like the guestbook, proving that you are not just a task-completer, but a thoughtful professional.</p>
<p><strong>Graduation and Beyond</strong></p>
<p>By completing this final hub, you earn the **Digital Citizen badge**, which signals that you can use digital tools effectively, safely, and responsibly in daily and professional life. The folder link you generate today is not just a homework submission; it is a permanent asset. You can attach this link to job applications, share it with prospective clients on WhatsApp, or show it to family to prove your digital literacy. This is the official launch of your new digital life.</p>
"""
}

def update_db():
    if not DB_PATH.exists():
        print(f"Error: Database not found at {DB_PATH}")
        return

    conn = sqlite3.connect(str(DB_PATH))
    cur = conn.cursor()

    print("Starting curriculum update...")
    
    for day in range(1, 21):
        # Fetch current record
        row = cur.execute("SELECT lesson_html, title FROM curriculum WHERE day=?", (day,)).fetchone()
        if not row:
            print(f"Day {day} not found in DB!")
            continue
            
        current_html, title = row
        
        if day in NEW_CORE_CONCEPTS:
            new_cc = NEW_CORE_CONCEPTS[day].strip()
            
            # Simple, bulletproof replacement of Core Concepts block
            # We look for <h3>Core Concepts</h3> and <h3>Key Terms</h3>
            # and replace the content in between.
            
            cc_header = "<h3>Core Concepts</h3>"
            kt_header = "<h3>Key Terms</h3>"
            
            if cc_header in current_html and kt_header in current_html:
                parts1 = current_html.split(cc_header)
                before_cc = parts1[0]
                after_cc_raw = parts1[1]
                
                parts2 = after_cc_raw.split(kt_header)
                after_cc = parts2[1]
                
                # Combine
                updated_html = f"{before_cc}{cc_header}\n{new_cc}\n\n{kt_header}{after_cc}"
            else:
                # If tags differ in casing or spacing, use regex
                # Find the text between Core Concepts and Key Terms
                pattern = re.compile(r'(<h3>Core Concepts</h3>)(.*?)(<h3>Key Terms</h3>)', re.DOTALL | re.IGNORECASE)
                if pattern.search(current_html):
                    updated_html = pattern.sub(rf'\1\n{new_cc}\n\n\3', current_html)
                else:
                    print(f"WARNING: Could not parse headers for Day {day}. Skipping replacement.")
                    updated_html = current_html
        else:
            updated_html = current_html

        # Update in database: write HTML and set status to 'published'
        cur.execute(
            "UPDATE curriculum SET lesson_html=?, lesson_status='published' WHERE day=?",
            (updated_html.strip(), day)
        )
        print(f"Day {day:2d} updated and published: {title}")

    conn.commit()
    conn.close()
    print("Database updates completed successfully.")

if __name__ == "__main__":
    update_db()
